name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
          uses: actions/setup-node@v2
          run: |
            npm ci
            npm run export
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://999md-client.vercel.app/en-US/
            https://999md-client.vercel.app/
          budgetPath: './.github/workflows/budget.json' # test performance budgets
          configPath: './.github/workflows/lighthouserc.json'
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage