name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install && npm install -g @lhci/cli@0.8.x
      - run: npm run build
      - run: sudo apt-get install -y wget
      - run: sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo apt-get install ./google-chrome-stable_current_amd64.deb
      - run: lhci autorun --config=./.github/workflows/lighthouserc.json
        env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}